### ISSUE TITLE
Action should evaluate all pages of `Get all package versions` API response

### ISSUE THREAD

**Issue by ohueter** [snok/container-retention-policy#33]
The script calls the GitHub API to get all versions for a given package name. There are different API routes depending on if the repo belongs to a user or an organization:

- User: https://docs.github.com/en/rest/packages#get-all-package-versions-for-a-package-owned-by-the-authenticated-user
- Orga: https://docs.github.com/en/rest/packages#get-all-package-versions-for-a-package-owned-by-an-organization

The list in the API response contains the latest 100 images at most, and there seems to be no way of setting the sort order. As a result, when there are more than 100 images that are newer than the cut-off date specified in the action, no images are ever deleted.

The action should walk all the pages by following the `link` response header, e.g. `<https://api.github.com/organizations/<org>/packages/container/<image>/versions?per_page=100&page=2>; rel="next", <https://api.github.com/organizations/<org>/packages/container/<image>/versions?per_page=100&page=13>; rel="last"`, gather all image names, and start deleting from the end.

**Comment by ohueter** [comment]
I'll try to fit it in sometime but unfortunately cannot make any promises here :) Will keep you posted.

**Comment by sondrelg** [comment]
Would we need to traverse until we fail? In other words, is there no way of knowing if there's a page `n+1`? Would be nice if there was a `total_pages`, but I suppose it doesn't really matter that much

**Comment by ohueter** [comment]
The link tagged with `rel="next"` is not present in the header if there is no next page (page `n+1` in your words).

**Comment by lukasz-mitka** [comment]
#42

**Comment by sondrelg** [comment]
This should be resolved in the main branch. Are you available to test it @ohueter? You should be able to check by using `@main` instead of, e.g., `@v1` in the action tag

**Comment by sondrelg** [comment]
v2 is now released, so think this can be closed. Let me know if you have any issues :slightly_smiling_face:
