### ISSUE TITLE
Add a dry-run

### ISSUE THREAD

**Issue by lukasz-mitka** [snok/container-retention-policy#34]
### What
Add a dry-run parameter
### How
Boolean, default to false.
When set to true it should print the `image:tag` combinations it would remove without actually removing anything.
### Why
So I'm able to do a dry-run when setting this up, so I can check if it deletes only the images I actually want.

**Comment by sondrelg** [comment]
Is still something you think you need @lukasz-mitka?

**Comment by sondrelg** [comment]
Closing this for now, due to a lack of response. Please feel free to reopen :)
