### ISSUE TITLE
Switch to composite action

### ISSUE THREAD

**Issue by lukasz-mitka** [snok/container-retention-policy#35]
Please consider switching to composite action instead of Dockerfile.
https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

Should be a bit faster since it wouldn't need to download python image or build-base.

**Comment by sondrelg** [comment]
Feel free to open a PR if youd like 👍

**Comment by sondrelg** [comment]
Resolved by #36. Thanks @lukasz-mitka, I'll release after we discuss major/minor release choice in the PR :+1:

**Comment by lukasz-mitka** [comment]
Guess it could be bundled for major release together with #42

**Comment by sondrelg** [comment]
Yep I like the sound of that :+1: I'll wait to release this then, and I'm sure you already know, but in case you don't: you should be able to run the main branch by specifying `@main` instead of `@v1` in the meantime if you want :slightly_smiling_face:
