### ISSUE TITLE
Cleanup all image?

### ISSUE THREAD

**Issue by dyipon** [snok/container-retention-policy#37]
Hi,

is there any way to cleanup all image (i mean all packages), without giving the exact names of images?

thanks

**Comment by dyipon** [comment]
@sondrelg are we talk about the same? :)
https://github.com/snok/container-retention-policy#image-names
I can't find any mask option here, doc says _"Takes one or several container image names as a comma separated list."_

**Comment by sondrelg** [comment]
No you're right there's no way of doing this currently. It seems like it would be possible to add, and I suppose it would be a nice way to se an org/user-wide retention policy, so I like the suggestion 😊

Would you be interested in creating a PR for this?

API docs can be found here: https://docs.github.com/en/rest/packages

I think for the implementation we would need to add a call to fetch all packages, then filter the results by the image name input- but that should be about it I think. Do you agree?

**Comment by dyipon** [comment]
I wish I would have any Python knowledge to implement this solution :~
But I agree, that would be the best solution which you described above.
Please leave this ticket open, I will try to refresh my python knowledge later this summer :)

**Comment by sondrelg** [comment]
Hello again @dyipon 🙂 Could you please try out the feature branch for this feature?

If you update your workflow to reference:

```diff
-snok/container-retention-policy@v1
+snok/container-retention-policy@add-packages-fetch
```

that should run the action using the feature branch. 

Wildcard should now be supported 👍 See #39 for some new WIP docs

**Comment by dyipon** [comment]
@sondrelg wow, that was really fast! This new feature branch is working fine, thanks for  your work!
