### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by bmoon4** [snok/container-retention-policy#46]
Github Actions is deprecating `set-output` command soon.

![image](https://user-images.githubusercontent.com/28991527/195689324-2784ca5b-7446-4219-96b6-2103cc6f9574.png)

```bash
Warning: The `set-output` command is deprecated and will be disabled soon. 
Please upgrade to using Environment Files. 
For more information see: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

So following lines need to be reviewed / fixed. 

https://github.com/snok/container-retention-policy/blob/main/.github/workflows/clean_packages.yml#L66

https://github.com/snok/container-retention-policy/blob/main/main.py#L509

https://github.com/snok/container-retention-policy/blob/main/main_tests.py#L578-L580

**Comment by sondrelg** [comment]
Neat, thanks for letting me know. Would you be interested in creating a fix?
