### ISSUE TITLE
Unhandled exception raised at runtime: `'x-ratelimit-remaining'`.

### ISSUE THREAD

**Issue by id-tari** [snok/container-retention-policy#57]
Running action v2.
During the first run it has discovered and deleted 147 untagged, 1 week old images.
By the end action throws exception messages:

```
Unhandled exception raised at runtime: `'x-ratelimit-remaining'`. Please report this at https://github.com/snok/container-retention-policy/issues/new
```
604 times/log-lines

Unfortunately there are no additional outputs, and action did not exit with error.
Action has finished "successfully".

Initially as test I was trying to delete only untagged, at least 1 week old images.
After initial run I had left 521 untagged image.

2nd run has discovered 70 images for deletion. Tons of exception messages still appear.
3rd run deleted 96 images.
4th run deleted 61 images. etc ...

Even "enable debug output" on action run is not showing anything useful.
I'm not sure how to debug this behavior, will greatly appreciate your ideas. (not a pro python developer)

**Comment by sondrelg** [comment]
Thanks @id-tari, the error you see is the "catch-all" exception handler [here](https://github.com/snok/container-retention-policy/blob/main/main.py#L417) :+1: 

If I had to guess, I'm assuming the response from github doesn't contain the `x-ratelimit-remaining` header we're expecting [here](https://github.com/snok/container-retention-policy/blob/main/main.py#L74). We should probably change this code to:

```diff
-    if int(response.headers['x-ratelimit-remaining']) == 0:
+    if int(response.headers.get('x-ratelimit-remaining', default=0)) == 0:
```

That's just my first instinct - could be wrong :slightly_smiling_face: 

Would you be interested in trying to create a fix? If you're comfortable with it, how you would need to do it is:

1. Fork this project
2. Commit the change above
3. Then in your workflow, to test it works, you can change

**Comment by Pho3niX90** [comment]
Same same. just posting here so there are no duplications. 
![image](https://github.com/snok/container-retention-policy/assets/7858187/08bf027b-b130-4606-bf93-cdc972c69e3f)

**Comment by sondrelg** [comment]
Thanks @Pho3niX90. I must have missed the PR for this. If I can I'll take a look and get it merged this weekend :+1:
