### ISSUE TITLE
You have exceeded a secondary rate limit

### ISSUE THREAD

**Issue by den-is** [snok/container-retention-policy#59]
Got another Warning/Notification while trying to delete "not-that-small" (a not that huge either) amount of images.
```
Couldn't delete xxxxxxx/yyyy:77988391.
Status code: 403
Response: {'documentation_url': 'https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits', 'message': 'You have exceeded a secondary rate limit. Please wait a few minutes before you try again.'}
```

**Comment by sondrelg** [comment]
Sorry for the lack of a response here @den-is. This issue will be fixed in the upcoming v3 release where we handle all secondary rate limits 👍 I'll update this issue when it's released.

**Comment by sondrelg** [comment]
The latest release redoes rate limiting completely. It should fix this issue, and a few more. That said, you can risk running into this, even in the new version, if you run multiple processes at the same time. For single runs however, we now handle secondary rate limits gracefully.

If you have time, the migration guide for v3 is included in the [release post](https://github.com/snok/container-retention-policy/releases/tag/v3.0.0) 👍 I would greatly appreciate feedback if you have any.

If you run into any issues, please share them in [the issue opened for tracking the v3 release](https://github.com/snok/container-retention-policy/issues/84) ☺️
