### ISSUE TITLE
Actions using v2 broke last night with System.ArgumentException (found BasicExpressionToken not MappingToken)

### ISSUE THREAD

**Issue by gregschmit** [snok/container-retention-policy#80]
A couple pipelines that use this action started breaking sometime last night. Here is the error:

```
##[debug]action.yml for action: '/home/runner/work/_actions/snok/container-retention-policy/v2/action.yml'.
Error: System.ArgumentException: Unexpected type 'BasicExpressionToken' encountered while reading 'env'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Failed to load snok/container-retention-policy/v2/action.yaml
##[debug]System.ArgumentException: Failed to load snok/container-retention-policy/v2/action.yaml
```

I initially thought it might have to do with GitHub's runners because I was using `v2` and on the main page it says that the last version was released Dec 8, 2023. However another user pointed out WIP commits on the `v2` branch that seem to be the wrong syntax: https://github.com/snok/container-retention-policy/blame/3f4828a74358cd42680e02853e5202ebff46bc2c/action.yaml#L72 (it should be a `:` not an `=`)

Example of failing job that worked earlier last night but fails now: https://github.com/gregschmit/rails-rest-framework/actions/runs/9167963220/job/25236841960

**Comment by gregschmit** [comment]
Also, is there a more stable branch I should point to that won't get wip commits?

**Comment by gregschmit** [comment]
I submitted a PR that fixes the argument exception, however perhaps you want to just take the wip commits off the v2 branch? I will close out my PR if you fix it another way.

Thanks!

**Comment by sondrelg** [comment]
I've clearly misnamed by rewrite-branch. Sorry for the disruption. I've deleted it now, so things should go back to normal.

I'm working on a rewrite, and happened to choose `v2` as the branch name, not taking into consideration that users might be tracking this tag 🙈
