### ISSUE TITLE
Use provided `GITHUB_*` variables

### ISSUE THREAD

**Issue by rkarp** [snok/container-retention-policy#86]
As it is now, self-hosted GitHub via GitHub Enterprise Server is not supported because the GitHub URLs are hardcoded: https://github.com/snok/container-retention-policy/blob/b439c10ae57ac70bd2301813dc2d0f708dc78f31/src/client/urls.rs#L14-L15

It looks like one can just use the `GITHUB_*` variables instead: https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

They may also be useful to provide defaults for things like "account".

**Comment by sondrelg** [comment]
Nice, so we should be able to use `GITHUB_API_URL` for the API URL and `GITHUB_SERVER_URL` for the server URL. That seems like a clear improvement 👏 Would you be interested in creating a PR @rkarp?

Thinking about whether you can use github context for account, I think you'd lose the ability to delete package versions from a different org., given you had a valid PAT 🤔 That might not be a good enough reason not to implement something like this, but seems like it would need a bit more consideration.

**Comment by rkarp** [comment]
I've created an initial implementation just for the GitHub URLs (see commit above), waiting for PR #87 first before I'll create a PR for this one.

Also, there's an interesting clap functionality that might be useful later: You can load default values from environment variables via the clap `env` arg attribute, see: https://docs.rs/clap/latest/clap/_derive/index.html#arg-attributes

**Comment by sondrelg** [comment]
Fixed in #88. Cheers @rkarp 🙂
